version: '3'
services:
  postgres:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=grocery_user
      - POSTGRES_PASSWORD=grocery_password
      - POSTGRES_DB=grocery_db
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgres_files:/usr/src
    ports:
      - 5433:5432
      